### PR TITLE
fix(searchbar): changed event listener to click

### LINKED ISSUE #373: [Docs] Enable Site Search with Button Click
#### Current State
Clicking on the search button doesn't search the site.

#### Desired State
Screenshot 2024-09-20 at 4 05 58 PM

---

#### Contributor Guide and Resources
- 📚 [Instructions for contributing to documentation](https://github.com/layer5io/docs/blob/master/CONTRIBUTING.md)
   - Layer5 documentation [site](https://docs.layer5.io) and [source](https://github.com/layer5io/docs/)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by void-hr**
**Notes for Reviewers**

This PR fixes #373

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by yash37158** [comment]
@void-hr  Ensure that the button click event does not cause a focus shift by preventing the default behavior and explicitly managing focus. also for Event bubbling If the flickering is due to event bubbling, make sure to stop the propagation of the event to other elements that might be causing the focus shift.

File: assets/js/offline-search.js [hunk 1]
```diff
@@ -1,208 +1,212 @@
...
+    //close the search panel when the ESC key is pressed
+    $(document).on("keydown", function (event) {
+      if (event.key === "Escape") {
+        $searchInput.val("");
+        $searchInput.trigger("change");
+      }
+    });
+    $searchInput.on("keydown", (event) => {
+      if (event.key === "Enter") {
+        event.preventDefault();
```
Comment (yash37158) [inline assets/js/offline-search.js:207]: Remember to prevent the event from bubbling up and use event.stopPropagation() to prevent the event from bubbling further.

File: layouts/partials/hotkey.html [hunk 2]
```diff
@@ -13,11 +13,16 @@
...
 />
 <script>
-  searchKey.addEventListener("mousedown", () => {
+  function focusSearchBar ()   {
+    var searchBar = document.querySelector(".td-search__input");
+    searchBar.focus();
+  };
+  
+  searchKey.addEventListener("click", () => {
     event.preventDefault();
```
Comment (yash37158) [inline layouts/partials/hotkey.html:22]: Same for the hotkey as well.

**Comment by vishalvivekm** [comment]
@void-hr This is hard to review, will you please revert lint changes ?

Let's discuss this during the website call on Monday at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by void-hr** [comment]
@vishalvivekm, reverted lint changes can you now take a look!

**Comment by vishalvivekm** [comment]
Thanks @void-hr 
Let's discuss this during the website call today at 5:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by leecalcote** [comment]
@yash37158 how are we doing here?

**Comment by leecalcote** [comment]
Thanks for working on this, @void-hr!

**Comment by leecalcote** [comment]
If you haven't joined the [Layer5 Community Slack](https://slack.layer5.io), yet, I invite you to jump in.

**Comment by void-hr** [comment]
> If you haven't joined the [Layer5 Community Slack](https://slack.layer5.io), yet, I invite you to jump in.

Thanks for the invite, however I am there from past 2 weeks I guess 🤔

**Review by yash37158 — APPROVED** [review]
LGTM @void-hr

**Review by vishalvivekm — APPROVED** [review]
Thank much @void-hr.
LGTM :smile:
